---
apiVersion: github.platform.benkeil.de/v1alpha1
kind: Repository
metadata:
  name: alarm-notification
  namespace: pdh-da
spec:
  full_name: otto-ec/pdh-da_alarm-notification
  delete_branch_on_merge: true
  security_and_analysis:
    advanced_security:
      status: enabled
    secret_scanning:
      status: enabled
    secret_scanning_push_protection:
      status: enabled
    dependabot_security_updates:
      status: enabled
    secret_scanning_validity_checks:
      status: enabled
  owner: otto-ec/pdh-distribution-analytics

  status:
    owner: otto-ec/pdh-distribution-analytics

---
apiVersion: github.platform.benkeil.de/v1alpha1
kind: AutolinkReference
metadata:
  name: alarm-notification-jira-dv
  namespace: pdh-da
spec:
  full_name: otto-ec/pdh-da_alarm-notification
  key_prefix: "DV-"
  url_template: "https://otto-eg.atlassian.net/browse/DV-<num>"
  is_alphanumeric: false

---
apiVersion: github.platform.benkeil.de/v1alpha1
kind: RepositoryPermission
metadata:
  name: alarm-notification
  namespace: pdh-da
spec:
  full_name: otto-ec/pdh-da_alarm-notification
  full_team_name: otto-ec/other-team-that-needs-to-work-at-the-repo
  permission: admin

---
apiVersion: github.platform.benkeil.de/v1alpha1
kind: RepositoryPermission
metadata:
  name: alarm-notification
  namespace: pdh-da
spec:
  full_name: otto-ec/pdh-da_alarm-notification
  user_name: benkeil
  permission: admin
