apiVersion: platform.benkeil.de/v1alpha1
kind: GitHubRepository
metadata:
  name: alarm-notification
  namespace: pdh-da
spec:
  full_name: otto-ec/pdh-da_alarm-notification
  repository:
    delete_branch_on_merge: false
    security_and_analysis:
      secret_scanning:
        status: disabled
      secret_scanning_push_protection:
        status: disabled
      dependabot_security_updates:
        status: disabled
      secret_scanning_validity_checks:
        status: disabled
#  autolink_references:
#    - key_prefix: "DV-"
#      url_template: "https://otto-eg.atlassian.net/browse/DV-<num>"
#      is_alphanumeric: false