apiVersion: platform.benkeil.de/v1alpha1
kind: GitHubRepository
metadata:
  name: alarm-notification
  namespace: pdh-da
spec:
  full_name: otto-ec/pdh-da_alarm-notification
  repository:
    delete_branch_on_merge: true
    security_and_analysis:
      secret_scanning:
        status: enabled
      secret_scanning_push_protection:
        status: enabled
      dependabot_security_updates:
        status: enabled
      secret_scanning_validity_checks:
        status: enabled
  autolink_references:
    - key_prefix: "DV-"
      url_template: "https://otto-eg.atlassian.net/browse/DV-<num>"
      is_alphanumeric: false
    - key_prefix: "DV-"
      url_template: "https://otto-eg.atlassian.net/browse/DV-<num>"
      is_alphanumeric: false